name: RA STORIES
favicon: null
layout_spectrum: 0.3888014785479754
typography_spectrum: 0.5629556861240417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7568022888153791
  lightness: 0.9835730174090713
  saturation: 0.9177203229628503
  rhythmicContrast: 0.5771961656864733
purpose: []
